version: 2
jobs:
  build:
    context: Koenighotze
    environment:
      IMAGE_NAME: koenighotze/render-manifests
      RELEASE_TAG: "1.0"
    docker:
      - image: docker:18.06.0-ce

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build docker image
          command: |
            docker build -t "${IMAGE_NAME}:${CIRCLE_SHA1}" --build-arg NAME="${IMAGE_NAME}" --build-arg CREATED="n/a" --build-arg TITLE="Kubernetes manifest render" --build-arg REVISION="$CIRCLE_SHA1" --build-arg BUILD_URL="$CIRCLE_BUILD_URL" --build-arg SOURCE="$CIRCLE_REPOSITORY_URL" .
            docker tag "${IMAGE_NAME}:${CIRCLE_SHA1}" "${IMAGE_NAME}:${RELEASE_TAG}"

      - run:
          name: Push docker image to Docker Hub
          command: |
            echo $DOCKERHUB_LOGIN_PASSWORD | docker login --username koenighotze --password-stdin
            docker push $IMAGE_NAME:$CIRCLE_SHA1
            docker push $IMAGE_NAME:$RELEASE_TAG
